name: John Murphy Institute
favicon: null
layout_spectrum: 0.74667
typography_spectrum: 0.672
title: John Murphy Institute for At-Risk Plush
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ef3f23'
    - '#295b9c'
    - '#6b80b4'
    - '#d3d7e9'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.25
purpose: []
