name: John Murphy Institute
favicon: null
layout_spectrum: 0.75292
typography_spectrum: 0.672
title: John Murphy Institute for At-Risk Plush
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebd8ba'
    - '#a29078'
    - '#9d2f14'
    - '#ff833e'
    - '#397c8c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6437325363513082
  rhythmicContrast: 0.25
purpose: []
