name: John Murphy Institute
favicon: null
layout_spectrum: 0.75459
typography_spectrum: 0.34479
title: John Murphy Institute for At-Risk Plush
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2aa84'
    - '#f3ec80'
    - '#ff7733'
    - '#55150a'
    - '#437e85'
  brandStrength: 0.9332821294665337
  lightness: 0.5
  saturation: 0.6437325363513082
  rhythmicContrast: 0.25
purpose: []
