name: John Murphy Institute
favicon: null
layout_spectrum: 0.04439572407864034
typography_spectrum: 0.29805
title: John Murphy Institute for At-Risk Plush
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ef4023'
    - '#2b5b9c'
    - '#0000ff'
    - '#000000'
    - '#00ffff'
  brandStrength: 0.9332821294665337
  lightness: 0.7770712831988931
  saturation: 0.6437325363513082
  rhythmicContrast: 0.9585318947210908
purpose: []
